"""Generate debian/upstream.md from a verified resolution.

One source of truth: the file is rendered from the same UpstreamResolution the
dashboard shows, so the committed record and the tool can never disagree.

Generation is deterministic - the same resolution renders byte-identical output,
with no timestamps or local paths - because the file is compared against what is
already in the repository to decide whether anything needs to change at all.

Nothing here writes to a repository. It reports CREATED, UPDATED, NO_CHANGE or
CONFLICT and hands the content back; committing is a separate, explicit act.
"""

from __future__ import annotations

import difflib
import logging
import re
from typing import List, Optional

from ..domain.enums import ResolutionStatus, UpstreamMdOutcome
from ..domain.models import UpstreamMdDocument, UpstreamResolution

log = logging.getLogger(__name__)

UPSTREAM_MD_PATH = "debian/upstream.md"
NONE = "N/A"

HEADER = "<!-- Generated by the ARCoS Package Manager. Edits are preserved: "\
         "regeneration reports a conflict rather than overwriting them. -->"

# A hand-edited file is one that no longer matches anything this tool would
# produce. Recognising our own marker is what makes that distinction possible.
MARKER = "Generated by the ARCoS Package Manager"


class UpstreamMdService:
    def render(self, resolution: UpstreamResolution) -> str:
        """The file, in the layout the requirement asks for.

        Nothing here is invented: every line is a field of the resolution, and a
        field that is not known says so rather than being filled in with a
        plausible value. A NEEDS_REVIEW package therefore records that it is
        unresolved and why - never an upstream that was not established.
        """
        debian = resolution.debian
        upstream = resolution.upstream_repository
        verified = resolution.status is ResolutionStatus.VERIFIED

        lines: List[str] = [
            HEADER,
            "",
            "# Upstream Information",
            "",
            "## Package",
            "",
            resolution.package,
            "",
            "## ARCoS",
            "",
            f"- Repository: {_or_none(resolution.github_repository)}",
            f"- Release: {_or_none(resolution.arcos_release)}",
            f"- Branch: {_or_none(resolution.arcos_branch)}",
            f"- Path: {_or_none(resolution.arcos_path)}",
            f"- Commit: {_or_none(resolution.arcos_commit)}",
            "",
            "## Debian",
            "",
            f"- Release: {resolution.debian_release}",
            f"- Source package: {_or_none(debian.source_package if debian else None)}",
            f"- Version: {_or_none(debian.version if debian else None)}",
            f"- VCS repository: {_or_none(debian.vcs_git if debian else None)}",
            f"- VCS branch: {_or_none(debian.vcs_branch if debian else None)}",
            "",
            "## Upstream",
            "",
        ]

        if upstream and upstream.url:
            # A resolution that only knows "the ref" - a manual one, or a row
            # from an older mapping - still has to show what is tracked, so the
            # ref stands in for the branch unless it is known to be a tag.
            branch = resolution.upstream_branch or (
                None if resolution.upstream_tag else resolution.upstream_ref
            )
            lines += [
                f"- Repository: {upstream.url}",
                f"- Branch: {_or_none(branch)}",
                f"- Tag: {_or_none(resolution.upstream_tag)}",
                f"- Commit: {_or_none(resolution.upstream_commit)}",
                f"- Origin kind: {_or_none(resolution.origin_kind)}",
            ]
        else:
            lines.append(
                "No upstream repository has been established for this package."
            )

        lines += [
            "",
            "## Resolution",
            "",
            f"- Mode: {resolution.mode.value.capitalize()}",
            f"- Status: {resolution.status.value}",
            f"- Method: {resolution.method.value}",
            f"- Confidence: {resolution.confidence}",
            f"- Category: "
            f"{resolution.category.value if resolution.category else NONE}",
        ]
        if not verified:
            lines.append(f"- Reason: {_or_none(resolution.reason)}")

        lines += [
            "",
            "## Evidence",
            "",
            f"- Source: {_or_none(resolution.evidence_source)}",
            f"- URL: {_or_none(resolution.evidence_url)}",
            f"- Verification: {_or_none(resolution.verification)}",
        ]
        if resolution.merge_base:
            lines += [
                f"- Common ancestor: {resolution.merge_base}",
                f"- Commits behind upstream: {_or_none(resolution.behind)}",
                f"- ARCoS-only commits: {_or_none(resolution.arcos_only)}",
            ]

        trail = sorted({e.detail.strip() for e in resolution.evidence if e.detail})
        if trail:
            lines += ["", "### Evidence trail", ""]
            lines += [f"- {item}" for item in trail]

        return "\n".join(lines).rstrip() + "\n"

    def generate(self, resolution: UpstreamResolution,
                 existing: Optional[str] = None) -> UpstreamMdDocument:
        """Render the file and say what writing it would do."""
        if resolution.status is ResolutionStatus.NO_UPSTREAM:
            raise ValueError(
                f"{resolution.package} has no upstream, so there is nothing to "
                f"record in {UPSTREAM_MD_PATH}."
            )

        content = self.render(resolution)
        document = UpstreamMdDocument(
            package=resolution.package,
            debian_release=resolution.debian_release,
            path=UPSTREAM_MD_PATH,
            content=content,
            existing_content=existing,
        )

        if existing is None:
            document.outcome = UpstreamMdOutcome.CREATED
            return document

        if _normalise(existing) == _normalise(content):
            document.outcome = UpstreamMdOutcome.NO_CHANGE
            return document

        document.diff = _diff(existing, content)
        # A file we did not write may carry information this tool does not know
        # about, so replacing it is a decision for a person.
        document.outcome = (
            UpstreamMdOutcome.UPDATED if MARKER in existing
            else UpstreamMdOutcome.CONFLICT
        )
        return document


def _or_none(value) -> str:
    if value is None or value == "":
        return NONE
    return str(value)


def _normalise(text: str) -> str:
    """Compare on content, not on trailing whitespace or line endings."""
    return "\n".join(
        line.rstrip() for line in re.sub(r"\r\n?", "\n", text or "").split("\n")
    ).strip()


def _diff(existing: str, generated: str) -> str:
    return "".join(
        difflib.unified_diff(
            (existing or "").splitlines(keepends=True),
            (generated or "").splitlines(keepends=True),
            fromfile=f"a/{UPSTREAM_MD_PATH}", tofile=f"b/{UPSTREAM_MD_PATH}",
        )
    )
