"""Generate debian/upstream.md from a verified resolution.

One source of truth: the file is rendered from the same UpstreamResolution the
dashboard shows, so the committed record and the tool can never disagree.

Generation is deterministic - the same resolution renders byte-identical output,
with no timestamps or local paths - because the file is compared against what is
already in the repository to decide whether anything needs to change at all.

Nothing here writes to a repository. It reports CREATED, UPDATED, NO_CHANGE or
CONFLICT and hands the content back; committing is a separate, explicit act.
"""

from __future__ import annotations

import difflib
import logging
import re
from typing import List, Optional

from ..domain.enums import ResolutionStatus, UpstreamMdOutcome
from ..domain.models import UpstreamMdDocument, UpstreamResolution

log = logging.getLogger(__name__)

UPSTREAM_MD_PATH = "debian/upstream.md"
NONE = "N/A"

HEADER = "<!-- Generated by the ARCoS Package Manager. Edits are preserved: "\
         "regeneration reports a conflict rather than overwriting them. -->"

# A hand-edited file is one that no longer matches anything this tool would
# produce. Recognising our own marker is what makes that distinction possible.
MARKER = "Generated by the ARCoS Package Manager"


class UpstreamMdService:
    def render(self, resolution: UpstreamResolution) -> str:
        """The file, in the layout the requirement asks for.

        Nothing here is invented: every line is a field of the resolution, and a
        field that is not known says so rather than being filled in with a
        plausible value. A NEEDS_REVIEW package therefore records that it is
        unresolved and why - never an upstream that was not established.
        """
        debian = resolution.debian
        upstream = resolution.upstream_repository
        verified = resolution.status is ResolutionStatus.VERIFIED

        lines: List[str] = [
            HEADER,
            "",
            "# Upstream Information",
            "",
            "## Package",
            "",
            resolution.package,
            "",
            "## ARCoS",
            "",
            f"- Repository: {_or_none(resolution.github_repository)}",
            f"- Release: {_or_none(resolution.arcos_release)}",
            f"- Branch: {_or_none(resolution.arcos_branch)}",
            f"- Path: {_or_none(resolution.arcos_path)}",
            f"- Commit: {_or_none(resolution.arcos_commit)}",
            "",
            "## Debian",
            "",
            f"- Release: {resolution.debian_release}",
            f"- Source package: {_or_none(debian.source_package if debian else None)}",
            f"- Version: {_or_none(debian.version if debian else None)}",
            f"- VCS repository: {_or_none(debian.vcs_git if debian else None)}",
            f"- VCS branch: {_or_none(debian.vcs_branch if debian else None)}",
            "",
            "## Upstream",
            "",
        ]

        if upstream and upstream.url:
            # A resolution that only knows "the ref" - a manual one, or a row
            # from an older mapping - still has to show what is tracked, so the
            # ref stands in for the branch unless it is known to be a tag.
            branch = resolution.upstream_branch or (
                None if resolution.upstream_tag else resolution.upstream_ref
            )
            lines += [
                f"- Repository: {upstream.url}",
                f"- Branch: {_or_none(branch)}",
                f"- Tag: {_or_none(resolution.upstream_tag)}",
                f"- Commit: {_or_none(resolution.upstream_commit)}",
                f"- Commit date: {_or_none(resolution.upstream_commit_date)}",
                f"- Origin kind: {_or_none(resolution.origin_kind)}",
            ]
        else:
            lines.append(
                "No upstream repository has been established for this package."
            )

        selection = resolution.ref_selection
        if selection is not None:
            contains = selection.arcos_contains_base
            lines += [
                "",
                "## Release reference",
                "",
                f"- Debian upstream version: {_or_none(selection.debian_upstream_version)}",
                f"- Target series: {_or_none(selection.series)}",
                f"- Upstream base tag: {_or_none(selection.base_tag)}"
                + (f" ({selection.base_sha[:12]})" if selection.base_sha else ""),
                f"- ARCoS contains the base tag: "
                f"{NONE if contains is None else ('yes' if contains else 'no')}",
                f"- Compared against: {selection.ref} ({selection.kind}, "
                f"{selection.strategy.value})",
                f"- Why: {_or_none(selection.reason)}",
                f"- Fallback ref: {'yes' if selection.is_fallback else 'no'}",
            ]

        lines += [
            "",
            "## Resolution",
            "",
            f"- Mode: {resolution.mode.value.capitalize()}",
            f"- Status: {resolution.status.value}",
            f"- Method: {resolution.method.value}",
            f"- Confidence: {resolution.confidence}",
            f"- Category: "
            f"{resolution.category.value if resolution.category else NONE}",
            f"- Verification level: {resolution.verification_level.value}",
            f"- Review reasons: "
            f"{', '.join(r.value for r in resolution.review_reasons) or 'none'}",
        ]
        if not verified:
            lines.append(f"- Reason: {_or_none(resolution.reason)}")
        curated = resolution.curated
        if curated is not None:
            lines.append(
                f"- Curated upstream: "
                + (f"{curated.repository} @ {curated.ref or 'HEAD'}"
                   if curated.repository else "no upstream")
                + (f" ({curated.reason})" if curated.reason else "")
            )
            if curated.conflict:
                lines.append(f"- Curated conflict: {curated.conflict}")

        lines += [
            "",
            "## Evidence",
            "",
            f"- Source: {_or_none(resolution.evidence_source)}",
            f"- URL: {_or_none(resolution.evidence_url)}",
            f"- Verification: {_or_none(resolution.verification)}",
        ]
        if resolution.merge_base:
            lines.append(f"- Common ancestor: {resolution.merge_base}")
        if len(resolution.merge_bases) > 1:
            lines.append(
                f"- Merge bases: {', '.join(resolution.merge_bases)} "
                f"(criss-cross history)"
            )
        if resolution.behind is not None or resolution.arcos_only is not None:
            arcos = (resolution.arcos_commit or "")[:12] or "ARCOS"
            up = (resolution.upstream_commit or "")[:12] or "UPSTREAM"
            lines += [
                f"- Upstream commits not in ARCoS (raw): {_or_none(resolution.behind)}",
                f"- ARCoS commits not in upstream (raw): {_or_none(resolution.arcos_only)}",
                f"- Count basis: {_or_none(resolution.counts_basis)}; "
                f"measured {arcos}..{up}"
                + ("; the upstream is the Debian packaging repository, so "
                   "packaging commits are included"
                   if resolution.origin_kind == "debian_packaging" else "")
                + ". These are not missing fixes - see Backlog.",
            ]

        match = resolution.content_match
        if match is not None and match.base_tag:
            lines += [
                "",
                "## Content match",
                "",
                f"- Method: {match.method}",
                f"- ARCoS tree compared: {_or_none(match.arcos_tree)} "
                f"({_or_none(match.arcos_tree_label)})",
                f"- Closest upstream tag: {match.base_tag}"
                + (f" ({match.base_sha[:12]})" if match.base_sha else ""),
                f"- Score: {(match.score or 0):.3f}",
                f"- Files differing: {_or_none(match.files_differing)} of "
                f"{_or_none(match.files_compared)}",
                f"- Lines differing: {_or_none(match.lines_differing)}",
                f"- Approved: "
                + (f"yes, by {match.verified_by} on {match.verified_at} "
                   f"({_or_none(match.approval_source)})"
                   if match.approved else "no - not used for any comparison"),
            ]
            if match.approved:
                lines.append(
                    "- Note: there is no shared git history. Any count above is "
                    "synthesized from this content match."
                )

        snapshot = resolution.comparison
        if snapshot is not None:
            lines += [
                "",
                "## Backlog",
                "",
                f"- Compared: ARCoS {snapshot.arcos_commit[:12]} against "
                f"{snapshot.upstream_ref} {snapshot.upstream_commit[:12]}",
                f"- Upstream base: {_or_none(snapshot.base_tag)}",
                f"- Target series: {_or_none(snapshot.series)}",
                f"- Relevant upstream commits: {snapshot.relevant_upstream}",
                f"- Already present: "
                f"{snapshot.definitely_present + snapshot.probably_present} "
                f"(definitely {snapshot.definitely_present}, probably "
                f"{snapshot.probably_present})",
                f"- Missing: {snapshot.missing}",
                f"- Unknown: {snapshot.unknown_presence}",
                f"- Reverted upstream (net no-op): {snapshot.reverted_upstream}",
                f"- Critical/security missing: {snapshot.critical_missing}",
                f"- Stable-nominated missing: {snapshot.stable_missing}",
                f"- Backport detection: {_or_none(snapshot.backport_detection)}",
            ]
            if snapshot.synthesized_ancestry:
                lines.append("- Ancestry: SYNTHESIZED from an approved content match")
            if snapshot.truncated:
                lines.append("- Note: the range was truncated for display; "
                             "unassessed commits are counted as Unknown")

        patches = resolution.debian_patches
        if patches is not None:
            lines += ["", "## Debian patches", ""]
            if not patches.available:
                lines.append(f"- Not available: {_or_none(patches.reason)}")
            else:
                security = patches.security_patches
                backports = [p for p in patches.patches
                             if p.category == "upstream_backport"]
                specific = [p for p in patches.patches
                            if p.category == "debian_specific"]
                lines += [
                    f"- Version: {patches.version}",
                    f"- Patches: {len(patches.patches)} (security "
                    f"{len(security)}, upstream backports {len(backports)}, "
                    f"Debian-specific {len(specific)})",
                    f"- CVEs referenced: {', '.join(patches.cve_ids) or 'none'}",
                    f"- Uploads of this upstream version: "
                    f"{', '.join(u.version for u in patches.uploads) or NONE}",
                ]
                for patch in security[:20]:
                    lines.append(
                        f"- Security patch: {patch.name} "
                        f"({', '.join(patch.cve_ids)})"
                    )
                if patches.reason:
                    lines.append(f"- Note: {patches.reason}")

        if resolution.warnings:
            lines += ["", "## Warnings", ""]
            lines += [f"- {w}" for w in resolution.warnings]

        trail = sorted({e.detail.strip() for e in resolution.evidence if e.detail})
        if trail:
            lines += ["", "### Evidence trail", ""]
            lines += [f"- {item}" for item in trail]

        return "\n".join(lines).rstrip() + "\n"

    def generate(self, resolution: UpstreamResolution,
                 existing: Optional[str] = None) -> UpstreamMdDocument:
        """Render the file and say what writing it would do."""
        if resolution.status is ResolutionStatus.NO_UPSTREAM:
            raise ValueError(
                f"{resolution.package} has no upstream, so there is nothing to "
                f"record in {UPSTREAM_MD_PATH}."
            )

        content = self.render(resolution)
        document = UpstreamMdDocument(
            package=resolution.package,
            debian_release=resolution.debian_release,
            path=UPSTREAM_MD_PATH,
            content=content,
            existing_content=existing,
        )

        document.outcome, diff = classify(existing, content)
        if document.outcome in (UpstreamMdOutcome.UPDATED,
                                UpstreamMdOutcome.CONFLICT):
            document.diff = diff
        return document


def classify(existing: Optional[str], content: str):
    """What writing `content` over `existing` would do, and the diff.

    Shared by generation and publishing, so the plan and the commit cannot reach
    different conclusions about the same file. `existing` is None when there is
    no file.
    """
    if existing is None:
        return UpstreamMdOutcome.CREATED, _diff("", content)
    if _normalise(existing) == _normalise(content):
        return UpstreamMdOutcome.NO_CHANGE, ""
    # A file we did not write may carry information this tool does not know
    # about, so replacing it is a decision for a person.
    outcome = (
        UpstreamMdOutcome.UPDATED if MARKER in existing
        else UpstreamMdOutcome.CONFLICT
    )
    return outcome, _diff(existing, content)


def _or_none(value) -> str:
    if value is None or value == "":
        return NONE
    return str(value)


def _normalise(text: str) -> str:
    """Compare on content, not on trailing whitespace or line endings."""
    return "\n".join(
        line.rstrip() for line in re.sub(r"\r\n?", "\n", text or "").split("\n")
    ).strip()


def _diff(existing: str, generated: str) -> str:
    return "".join(
        difflib.unified_diff(
            (existing or "").splitlines(keepends=True),
            (generated or "").splitlines(keepends=True),
            fromfile=f"a/{UPSTREAM_MD_PATH}", tofile=f"b/{UPSTREAM_MD_PATH}",
        )
    )
