#!/usr/bin/env python3
"""Check the generated debian/upstream.md files against the mapping they came from.

The whole point of generating them is that the committed record and the tool
cannot disagree. This re-reads the files as a stranger would and holds them
against the release CSV, so a renderer that quietly stops emitting a field, or
emits one the mapping does not support, is caught before anything is proposed.

    ./.venv/bin/python scripts/verify_upstream_md.py [bookworm]
"""

from __future__ import annotations

import csv
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

failures = []


def check(name: str, ok: bool, detail: str = "") -> None:
    print(("PASS  " if ok else "FAIL  ") + name + (f"  -> {detail}" if detail else ""))
    if not ok:
        failures.append(name)


def fields(text: str) -> dict:
    """The '- Key: value' lines, keyed by section so names cannot collide."""
    found, section = {}, ""
    for line in text.splitlines():
        if line.startswith("## "):
            section = line[3:].strip()
            continue
        match = re.match(r"^- ([^:]+): (.*)$", line)
        if match:
            found[f"{section}/{match.group(1).strip()}"] = match.group(2).strip()
    return found


def main(release: str) -> int:
    mapping_path = ROOT / "out" / f"upstream-mapping-{release}.csv"
    md_dir = ROOT / "out" / "upstream-md"
    plan_path = ROOT / "out" / f"upstream-md-plan-{release}.json"

    if not mapping_path.exists():
        print(f"no mapping at {mapping_path}", file=sys.stderr)
        return 2
    if not md_dir.exists():
        print(f"no generated files at {md_dir}", file=sys.stderr)
        return 2

    rows = {r["Package"]: r for r in csv.DictReader(mapping_path.open())}
    generated = {
        path.parent.parent.name: path
        for path in md_dir.glob("*/debian/upstream.md")
    }

    check("every generated file has a mapping row",
          all(p in rows for p in generated),
          ", ".join(sorted(set(generated) - set(rows))))

    # A file for a package with nothing to track would be fiction.
    invented = sorted(
        p for p in generated if rows.get(p, {}).get("Resolution Status") == "NO_UPSTREAM"
    )
    check("no file was generated for a NO_UPSTREAM package", not invented,
          ", ".join(invented))

    mismatches, unmarked = [], []
    for package, path in sorted(generated.items()):
        row = rows.get(package)
        if row is None:
            continue
        text = path.read_text()
        if "Generated by the ARCoS Package Manager" not in text:
            unmarked.append(package)
        value = fields(text)

        expected = {
            "ARCoS/Repository": row["ARCoS Repository"],
            "ARCoS/Release": row["ARCoS Release"],
            "ARCoS/Branch": row["ARCoS Branch"],
            "ARCoS/Path": row["ARCoS Path"],
            "Debian/Source package": row["Debian Source Package"],
            "Debian/Version": row["Debian Version"],
            "Debian/VCS repository": row["Debian VCS Repository"],
            "Debian/VCS branch": row["Debian VCS Branch"],
            "Upstream/Repository": row["Upstream Repository"],
            "Upstream/Branch": row["Upstream Branch"],
            "Upstream/Tag": row["Upstream Tag"],
            "Resolution/Status": row["Resolution Status"],
            "Evidence/Source": row["Evidence Source"],
            "Evidence/URL": row["Evidence URL"],
            "Evidence/Common ancestor": row["Common Ancestor"],
        }
        for key, want in expected.items():
            got = value.get(key, "<missing>")
            # An unestablished field is written as N/A, and a whole optional
            # block - the ancestry counts, for a package whose origin was not
            # probed - is left out rather than filled with placeholders. Both
            # mean the same thing as an empty mapping cell: not established.
            if got in ("N/A", "<missing>"):
                got = ""
            # The mapping shortens SHAs for reading.
            if want and len(want) == 12 and got.startswith(want):
                continue
            if got != want:
                mismatches.append(f"{package} {key}: file={got!r} mapping={want!r}")

    check("every file marks itself as generated", not unmarked, ", ".join(unmarked))
    check("every field matches the mapping row", not mismatches,
          "; ".join(mismatches[:5]))

    if plan_path.exists():
        plan = json.loads(plan_path.read_text())
        check("the plan pushed nothing", plan.get("pushed") is False)
        check("the plan created no pull request",
              plan.get("pull_requests_created") is False)
        planned = {e["package"] for e in plan["entries"]}
        check("the plan covers exactly the generated files",
              planned == set(generated),
              f"plan={len(planned)} files={len(generated)}")
        bad_base = [
            e["package"] for e in plan["entries"]
            if e["branch"] == e["base_branch"]
        ]
        check("no planned branch is the branch it targets", not bad_base,
              ", ".join(bad_base))
        outside = [
            e["package"] for e in plan["entries"]
            if not e["branch"].startswith("upstream-metadata/")
        ]
        check("every planned branch is under upstream-metadata/", not outside,
              ", ".join(outside))

        # The publisher commits these bytes only if they still hash to what
        # the plan recorded; say so here first rather than at push time.
        hashed = [e for e in plan["entries"] if e.get("sha256")]
        if hashed:
            changed = [
                e["package"] for e in hashed
                if e["package"] in generated and hashlib.sha256(
                    generated[e["package"]].read_bytes()
                ).hexdigest() != e["sha256"]
            ]
            check("every generated file still matches the plan's hash",
                  not changed, ", ".join(changed))
        else:
            print("  note  the plan has no content hashes; regenerate it before "
                  "publish-upstream-md")

    print()
    print(f"generated: {len(generated)}   mapping rows: {len(rows)}")
    print("FAILURES:", ", ".join(failures) if failures else "none")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else "bookworm"))
